name: acm4tw-env

channels:
  - conda-forge

dependencies:
  - python=3.11.9
  - jupyter=1.0.0
  - jupyterlab>=3.1
  - ipywidgets=7.5.1
  - matplotlib=3.4.1
  - numpy=1.20.2
  - scipy=1.6.2
  - pandas=1.2.4
  - seaborn>=0.12
  - voila>=0.2.11
